### ISSUE TITLE
Generate ExDoc looking websites from Rebar3+Edoc

### ISSUE THREAD

**Issue by josevalim** [erlef/build-and-packaging-wg#24]
- [x] Adopt EEP 48 on Edoc (assigned @erszcz)
- [ ] Support Erlang+EEP 48 on ExDoc (assigned @wojtekmach) ([ExDoc issue]( https://github.com/elixir-lang/ex_doc/issues/1333))
- [x] Add Rebar3 integration to Edoc+ExDoc

**Comment by starbelly** [comment]
One thing we could do is install ex_doc (escipt) along with rebar3_hex, as a dep,  when that's available ofc

**Comment by josevalim** [comment]
Yes. We can also automatically download it when you call rebar3 exdoc or similar. Multiple ideas to explore!

**Comment by paulo-ferraz-oliveira** [comment]
`rebar3 local install exdoc` 😄 (since `rebar3 local install` is already a thing)

**Comment by starbelly** [comment]
> `rebar3 local install exdoc` 😄 (since `rebar3 local install` is already a thing)

Yeah, it is better to be explicit here, I suppose it wouldn't be nice to just install an ex_doc escript automagically when someone installs rebar3_hex.

**Comment by paulo-ferraz-oliveira** [comment]
> Yeah, it is better to be explicit here, I suppose it wouldn't be nice to just install an ex_doc escript automagically when someone installs rebar3_hex

Or you could have an option in `rebar3_hex`'s: `install_exdoc`. Of course that would mean "local", not "global".

**Comment by starbelly** [comment]
Aside from the action items that have been completed or assigned. I think what needs to be figured out is thus : 

1. Does this get included as rebar3 itself as part of a new provider? That is up to @ferd and @tsloughter. I'm not opposed to it myself, but it would mean rebar3 grows more and more maintenance burden for @ferd and @tsloughter, which I do not like. So, very conflicting for me personally. 

2. If it doesn't get included in rebar3 itself, there must either be a rebar3 plugin shipped with ex_doc, which doesn't make a lot of sense, since the goal is to ship this for erlang project usage purposes compiled as an escript. 

3. If 1 and 2 hold true, then there must be a rebar plugin dedicated to this. 

4. Finally, where the ex_doc executable will live. The simplest way is to use github actions to create packages that can in turn be downloaded for use. 

If option 3 is the way to go then the flow for a rebar3_hex user would be thus : 

1. User adds plugin to their project_plugins or as a global plugin via their global rebar.config 
2. User sets `{doc, #{provider => ex_doc}}` or `#{doc => #{provider => ex_doc}}` (depending on their setup)

That's it, essentially.

**Comment by josevalim** [comment]
ExDoc is already usable for some Erlang projects, example PR here: https://github.com/beam-telemetry/telemetry/pull/81

**Comment by wojtekmach** [comment]
Regarding rebar3 integration, here's the list of manual steps that users are currently doing:

https://github.com/elixir-lang/ex_doc#using-exdoc-with-erlang-projects

**Comment by starbelly** [comment]
There's a task unchecked, but pretty sure that's done otherwise things wouldn't work. Thus, I think this can be closed now.
