### ISSUE TITLE
Erlang/OTP windows builds

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#26]
## Background

We're wanting to get in support for windows in erlef/setup-beam. There's a few existing examples go by for that work, but it seems optimal to get the builds from the OTP team itself. This also requires a builds list ala https://repo.hex.pm/builds/otp/ubuntu-18.04/builds.txt. This may already exist, but if so it's not clear where it is. 

If I recall correctly we had dialog before around the OTP team providing more builds on github for a wider array of operating systems and architectures, but I don't believe we executed on that per looking at what's available on github right now. 

As far as I'm aware the only place to find a windows build from OTP team is in http://erlang.org/download/ (or via the download page on erlang.org), however there is no textual list (either plain text ala hex build list or in json format). It may be required to build a matrix of windows / otp versions, but that is not clear to me per having little experience with windows and Erlang/OTP.  

While, getting packages on github may be an objective here, it's not clear whether that is really needed to for our goals. However, we need to the windows builds to be highly available which erlang.org may not be able to provide. 

Finally, per my limited experience with installing Erlang/OTP on windows it's not clear to me whether the existing builds can be installed unassisted (i.e., via the CLI). 
 
## Objective(s)

- [ ] Get a standardized windows build list either on erlang.org or on github
- [ ] Discuss the pros and cons (if any) of making windows builds available on github

**Comment by ferd** [comment]
You can now find auto-uploaded and pre-built executables on each releases on their github pages as well: https://github.com/erlang/otp/releases/tag/OTP-23.3.1

**Comment by ferd** [comment]
Eh nevermind I might be wrong on the automated nature, the smaller point releases don't have them https://github.com/erlang/otp/releases/tag/OTP-21.3.8.22

**Comment by starbelly** [comment]
I see. All we need is a list then, basically. I mean, we could just talk to github's api, but optimally we have one general way of getting a list, parsing it, etc.  Maybe some other things I'm not thinking about at the moment.

**Comment by paulo-ferraz-oliveira** [comment]
For `rebar3`, for example, and as per @ferd's suggestion, we are indeed getting the version list from the GitHub API (at https://api.github.com/repos/erlang/rebar3/releases), but I guess versioning is easier there because there's only one "binary", whereas for Erlang/OTP pre-built Windows versions (`.exe`) are different from Linux ones.

**Comment by josevalim** [comment]
> Eh nevermind I might be wrong on the automated nature, the smaller point releases don't have them https://github.com/erlang/otp/releases/tag/OTP-21.3.8.22 -- though that could be because they're older than the commits containing the hooks to build.

@jhogberg confirmed that it is automated and it happens for *all* releases since OTP 23.0. So we should be able to rely on precompiled releases from that version onwards (which in my opinion is a fine requirement to make).

**Comment by paulo-ferraz-oliveira** [comment]
https://api.github.com/repos/erlang/otp/releases 😄 and if they had a label "otp_win32" it'd be sweet 😄 At the same time, I guess I can parse those results and use the versions that are left over from e.g. `otp_win32_23.3.1.exe` by removal of prefix `otp_win2_` and suffix `.exe` (though it's kinda fragile, this way).

**Comment by jhogberg** [comment]
You should be able to use `git` for that, any tag that can reach `OTP-23.0` has Windows builds.
```
$ export RELEASE_TAG='tag goes here'
$ [[ -n $(git tag -l --merged $RELEASE_TAG 'OTP-23.0') ]] && \
        echo "$RELEASE_TAG has Windows builds" || \
        echo "$RELEASE_TAG does not have Windows builds"
```

**Comment by paulo-ferraz-oliveira** [comment]
@jhogberg, I need the information _before_ I download the package, since (at least in the `setup-beam` GitHub action) we provide for a semver-like version choice mechanism. It goes like this:

1. you choose your version (as an input parameter)
2. we verify that your version (e.g. `23.0`) is _known_ < this is where we need the list
3. we try to make a choice
3.1. if impossible (version not listed), we error out
3.2. if possible (version listed), we use semver-like version choice to choose a version (in the case of `23.0` this would be `>=23.0.0 <23.1.0-0`, then download the package

**Comment by wojtekmach** [comment]
I might be missing something but I believe instead of your condition being "has label otp_win32" it is "version is >= 23"? Yo can still grab the list of releases from https://api.github.com/repos/erlang/otp/releases.

**Comment by paulo-ferraz-oliveira** [comment]
@wojtekmach, I can use that condition, no prob. I was just stating that a label would help us not need to do an extra check. In any case, I can filter by name, hoping it'll always be consistent 😄

**Comment by wojtekmach** [comment]
I was able to create a sample project that uses official OTP windows builds on GitHub Actions:

- https://github.com/wojtekmach/test_erlang_windows/blob/main/.github/workflows/main.yml
- https://github.com/wojtekmach/test_erlang_windows/runs/2503726300?check_suite_focus=true

We still need to make it so that erlef/setup-elixir on Windows downloads and executes the installer but at least we know it's possible!

Thanks @jhogberg for mentioning that NSIS installers have an unattended flag (`/S`) which was the missing piece.

**Comment by wojtekmach** [comment]
This is a separate discussion but I was also able to easily install OTP on macOS using Homebrew (same idea as in https://github.com/asdf-vm/asdf-erlang/pull/190):

- https://github.com/wojtekmach/test_erlang/blob/43aa3eb3245db45cb7f39389eb14c67e724c43b9/.github/workflows/main.yml#L16:L20
- https://github.com/wojtekmach/test_erlang/runs/2503967498?check_suite_focus=true

**Comment by starbelly** [comment]
Closing this as resolved. setup-beam is now making use of windows builds from erlang/otp (via github).
